logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://14.63.166.136/test1?useUnicode=true&characterEncoding=utf-8
    username: pandora_ojt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
    
    
  jpa:
    show-sql: true
    generate-ddl: true
    
 
file:
  path: C:/workspace/image/
  
  
server:  mulipart:
    enabled: true
    max-file-size: 2MB