spring:
  datasource:
    url: jdbc:mysql://14.63.166.136/test1?useUnicode=true&characterEncoding=utf-8
    username: pandora_ojt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
    show-sql: true
    generate-ddl: true
    
  logging:
  file:
    name: ${user.dir}/log/test.log  # 로깅 파일 위치
    max-history: 7 # 로그 파일 삭제 주기, 7일 이후 로그는 삭제
    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈
    