logging:
  level:
    root: info
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tjdls@2278A
    driver-class-name: com.mysql.cj.jdbc.Driver
  
    
    
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    generate-ddl: true
    
file:
  path: C:/ecommerce/react/public/image/
  
  
server:  
  mulipart:
    enabled: true
    max-file-size: 2MB
 